// Code generated by protoc-gen-go. DO NOT EDIT.
// source: base.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Message represents what is the purpose of object
//
type Message int32

const (
	// Metadata of STORE action for wallet and user object
	Message_STORE_CACHE    Message = 0
	Message_STORE_CACHE_DB Message = 1
	Message_STORE_DB       Message = 2
	// Metadata of QUERY action for user object
	Message_QUERY_USER_ID    Message = 20
	Message_QUERY_USER_EMAIL Message = 21
)

var Message_name = map[int32]string{
	0:  "STORE_CACHE",
	1:  "STORE_CACHE_DB",
	2:  "STORE_DB",
	20: "QUERY_USER_ID",
	21: "QUERY_USER_EMAIL",
}

var Message_value = map[string]int32{
	"STORE_CACHE":      0,
	"STORE_CACHE_DB":   1,
	"STORE_DB":         2,
	"QUERY_USER_ID":    20,
	"QUERY_USER_EMAIL": 21,
}

func (x Message) String() string {
	return proto.EnumName(Message_name, int32(x))
}

func (Message) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{0}
}

// Object represents table/struct
//
// [USER]
type Object int32

const (
	Object_USER Object = 0
)

var Object_name = map[int32]string{
	0: "USER",
}

var Object_value = map[string]int32{
	"USER": 0,
}

func (x Object) String() string {
	return proto.EnumName(Object_name, int32(x))
}

func (Object) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{1}
}

// Action represents:
//
// STORE, QUERY
type Action int32

const (
	Action_STORE Action = 0
	Action_QUERY Action = 1
)

var Action_name = map[int32]string{
	0: "STORE",
	1: "QUERY",
}

var Action_value = map[string]int32{
	"STORE": 0,
	"QUERY": 1,
}

func (x Action) String() string {
	return proto.EnumName(Action_name, int32(x))
}

func (Action) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{2}
}

type BaseReq struct {
	Action               Action   `protobuf:"varint,1,opt,name=action,proto3,enum=protobuf.Action" json:"action,omitempty"`
	ObjectType           Object   `protobuf:"varint,2,opt,name=objectType,proto3,enum=protobuf.Object" json:"objectType,omitempty"`
	Message              Message  `protobuf:"varint,3,opt,name=message,proto3,enum=protobuf.Message" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseReq) Reset()         { *m = BaseReq{} }
func (m *BaseReq) String() string { return proto.CompactTextString(m) }
func (*BaseReq) ProtoMessage()    {}
func (*BaseReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{0}
}

func (m *BaseReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseReq.Unmarshal(m, b)
}
func (m *BaseReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseReq.Marshal(b, m, deterministic)
}
func (m *BaseReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseReq.Merge(m, src)
}
func (m *BaseReq) XXX_Size() int {
	return xxx_messageInfo_BaseReq.Size(m)
}
func (m *BaseReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseReq.DiscardUnknown(m)
}

var xxx_messageInfo_BaseReq proto.InternalMessageInfo

func (m *BaseReq) GetAction() Action {
	if m != nil {
		return m.Action
	}
	return Action_STORE
}

func (m *BaseReq) GetObjectType() Object {
	if m != nil {
		return m.ObjectType
	}
	return Object_USER
}

func (m *BaseReq) GetMessage() Message {
	if m != nil {
		return m.Message
	}
	return Message_STORE_CACHE
}

func init() {
	proto.RegisterEnum("protobuf.Message", Message_name, Message_value)
	proto.RegisterEnum("protobuf.Object", Object_name, Object_value)
	proto.RegisterEnum("protobuf.Action", Action_name, Action_value)
	proto.RegisterType((*BaseReq)(nil), "protobuf.BaseReq")
}

func init() { proto.RegisterFile("base.proto", fileDescriptor_db1b6b0986796150) }

var fileDescriptor_db1b6b0986796150 = []byte{
	// 243 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8f, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0xb3, 0x55, 0x93, 0xf8, 0xab, 0x75, 0x3a, 0x54, 0xc8, 0x49, 0xc4, 0x53, 0x89, 0x10,
	0x44, 0x9f, 0x20, 0x69, 0x16, 0x2c, 0x58, 0x8a, 0xdb, 0xf6, 0xe0, 0x29, 0x24, 0x65, 0x14, 0x05,
	0x4d, 0x35, 0xf1, 0xe0, 0x6b, 0xf8, 0xc4, 0xd2, 0xdd, 0x16, 0x83, 0xa7, 0x5d, 0xbe, 0xef, 0xdb,
	0x65, 0x06, 0xa8, 0xca, 0x46, 0x92, 0xf5, 0x67, 0xdd, 0xd6, 0x1c, 0xda, 0xa3, 0xfa, 0x7a, 0xba,
	0xfc, 0x51, 0x08, 0xb2, 0xb2, 0x11, 0x23, 0x1f, 0x3c, 0x82, 0x5f, 0xae, 0xda, 0x97, 0xfa, 0x3d,
	0x52, 0x17, 0x6a, 0xd4, 0xbf, 0xa1, 0x64, 0x97, 0x25, 0xa9, 0xe5, 0x66, 0xeb, 0xf9, 0x1a, 0xa8,
	0xab, 0x57, 0x59, 0xb5, 0x8b, 0xef, 0xb5, 0x44, 0xbd, 0xff, 0xf5, 0xcc, 0x3a, 0xd3, 0x69, 0xf8,
	0x0a, 0xc1, 0x9b, 0x34, 0x4d, 0xf9, 0x2c, 0xd1, 0x9e, 0xcd, 0x07, 0x7f, 0xf9, 0xd4, 0x09, 0xb3,
	0x2b, 0x62, 0x41, 0xb0, 0x65, 0x7c, 0x8a, 0xa3, 0xf9, 0x62, 0x66, 0x74, 0x31, 0x4e, 0xc7, 0x77,
	0x9a, 0x3c, 0x66, 0xf4, 0x3b, 0xa0, 0xc8, 0x33, 0x52, 0x7c, 0x8c, 0xd0, 0xb1, 0x3c, 0xa3, 0x1e,
	0x0f, 0x70, 0xf2, 0xb0, 0xd4, 0xe6, 0xb1, 0x58, 0xce, 0xb5, 0x29, 0x26, 0x39, 0x0d, 0x79, 0x08,
	0xea, 0x20, 0x3d, 0x4d, 0x27, 0xf7, 0x74, 0x16, 0x33, 0x7c, 0x37, 0x29, 0x87, 0xd8, 0xdf, 0x18,
	0xf2, 0xe2, 0x73, 0xf8, 0x6e, 0x57, 0x3e, 0xc4, 0x81, 0xfd, 0x94, 0xbc, 0xcd, 0xd5, 0x3e, 0x27,
	0x55, 0xf9, 0x76, 0xea, 0xdb, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6b, 0x8a, 0xb3, 0xf9, 0x4e,
	0x01, 0x00, 0x00,
}
